package io.github.javamodernizationlabs.jspecify.maven;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;

@Mojo(name = "nullaway-check", threadSafe = true, requiresProject = true)
public class NullAwayCheckMojo extends AbstractMojo {

    @Parameter(property = "jspecify.outputDirectory",
            defaultValue = "${project.build.directory}/reports/jml/jspecify")
    private File outputDirectory;

    @Parameter(property = "jspecify.nullaway.mode", defaultValue = "warn")
    private String mode;

    @Parameter
    private List<String> annotatedPackages;

    @Parameter
    private List<String> excludedClasses;

    @Override
    public void execute() throws MojoExecutionException {
        try {
            var out = outputDirectory.toPath();
            Files.createDirectories(out);
            String snippet = """
                    <!-- Generated by JSpecify Migration Kit. -->
                    <compilerArgs>
                      <arg>-XepOpt:NullAway:AnnotatedPackages=%s</arg>
                      <arg>-XepOpt:NullAway:ExcludedClasses=%s</arg>
                      <arg>-Xep:NullAway:%s</arg>
                    </compilerArgs>
                    """.formatted(
                    String.join(",", annotatedPackages == null ? List.of() : annotatedPackages),
                    String.join(",", excludedClasses == null ? List.of() : excludedClasses),
                    mode.equalsIgnoreCase("error") ? "ERROR" : "WARN");
            Files.writeString(out.resolve("nullaway-maven.xml"), snippet, StandardCharsets.UTF_8);
            getLog().info("JSpecify NullAway Maven config written to " + out);
        } catch (Exception e) {
            throw new MojoExecutionException("JSpecify NullAway config failed: " + e.getMessage(), e);
        }
    }
}
