package io.github.javamodernizationlabs.jspecify.gradle;

import org.gradle.api.DefaultTask;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.TaskAction;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

public abstract class JspecifyNullAwayCheckTask extends DefaultTask {

    @Input
    public abstract Property<Boolean> getNullAwayEnabled();

    @Input
    public abstract Property<String> getMode();

    @Input
    public abstract ListProperty<String> getAnnotatedPackages();

    @Input
    public abstract ListProperty<String> getExcludedClasses();

    @OutputDirectory
    public abstract DirectoryProperty getOutputDirectory();

    @TaskAction
    public void run() throws IOException {
        var output = getOutputDirectory().getAsFile().get().toPath();
        Files.createDirectories(output);
        String severity = getMode().getOrElse("warn").equalsIgnoreCase("error")
                ? "ERROR"
                : "WARN";
        String gradleSnippet = """
                // Generated by JSpecify Migration Kit.
                // Apply the Error Prone plugin, then add these NullAway options.
                tasks.withType(JavaCompile).configureEach {
                    options.errorprone {
                        option("NullAway:AnnotatedPackages", "%s")
                        option("NullAway:ExcludedClasses", "%s")
                        check("NullAway", CheckSeverity.%s)
                    }
                }
                """.formatted(
                String.join(",", getAnnotatedPackages().getOrElse(java.util.List.of())),
                String.join(",", getExcludedClasses().getOrElse(java.util.List.of())),
                severity);
        Files.writeString(output.resolve("nullaway.gradle.kts"), gradleSnippet,
                StandardCharsets.UTF_8);
        getLogger().lifecycle("JSpecify NullAway config written to {}", output);
    }
}
