package io.github.javamodernizationlabs.jspecify.cli;

import io.github.javamodernizationlabs.jspecify.config.JspecifyConfig;
import io.github.javamodernizationlabs.jspecify.config.JspecifyConfigLoader;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.Callable;

@Command(
        name = "nullaway-config",
        description = "Generate NullAway/Error Prone configuration snippets.",
        mixinStandardHelpOptions = true
)
public class NullAwayConfigCommand implements Callable<Integer> {

    @Option(names = {"--project"}, defaultValue = ".") Path project;
    @Option(names = {"--mode"}, defaultValue = "warn") String mode;
    @Option(names = {"--annotated-packages"}, split = ",") List<String> annotatedPackages;
    @Option(names = {"--excluded-classes"}, split = ",") List<String> excludedClasses;
    @Option(names = {"--output-dir"}) Path output;

    @Override
    public Integer call() throws Exception {
        Path projectRoot = project.toAbsolutePath().normalize();
        JspecifyConfig config = JspecifyConfigLoader.load(projectRoot);
        Path out = output == null
                ? config.resolveReportsOutputDirectory(projectRoot)
                : output.toAbsolutePath().normalize();
        Files.createDirectories(out);
        String severity = mode.equalsIgnoreCase("error") ? "ERROR" : "WARN";
        String snippet = """
                // Generated by JSpecify Migration Kit.
                tasks.withType(JavaCompile).configureEach {
                    options.errorprone {
                        option("NullAway:AnnotatedPackages", "%s")
                        option("NullAway:ExcludedClasses", "%s")
                        check("NullAway", CheckSeverity.%s)
                    }
                }
                """.formatted(
                String.join(",", annotatedPackages == null ? List.of() : annotatedPackages),
                String.join(",", excludedClasses == null ? List.of() : excludedClasses),
                severity);
        Files.writeString(out.resolve("nullaway.gradle.kts"), snippet, StandardCharsets.UTF_8);
        System.out.println("NullAway config written to " + out);
        return 0;
    }
}
